os: Visual Studio 2019
version: "{branch}-{build}"

clone_folder: c:\build

install:
  - ps: (new-object net.webclient).DownloadFile('http://coapp.org/files/CoApp.Tools.Powershell.msi', 'C:\CoApp.Tools.Powershell.msi')
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\CoApp.Tools.Powershell.msi', /quiet -Wait
  - ps: $env:PSModulePath = $env:PSModulePath + ';C:\Program Files (x86)\Outercurve Foundation\Modules'
  - ps: Import-Module CoApp

before_build:
  - nuget restore msvs_solution/msvs_solution.sln
  - nuget update msvs_solution/msvs_solution.sln

build_script:
  - ps: .\nuget\build_nuget.ps1

test_script:

deploy:
  provider: NuGet
  api_key:
    secure: qxvWZr7f20ca4xcBaBZfHxmG8VCzzgpATKTLR8C14vhSmIZrlPSxthvpTJcKgFJO
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true

artifacts:
  - path: .\nuget\*.nupkg
