branches:
  only:
    - master

os: Visual Studio 2017
version: "{branch}-{build}"

clone_folder: c:\projects\build

environment:
  PRORAB_GIT_USERNAME: igagis
  PRORAB_GIT_ACCESS_TOKEN:
    secure: mpW6B2ols1a2FkshjKjryBuvBt8A1TpU9WGn+/d6PIQiZlzA0Rpo1ETKpmy0bnvX
  DEPS: make,gcc-g++,prorab,utki,svgdom,libcairo-devel,libpugixml-devel,kolme


install:
  - cmd: C:\cygwin64\setup-x86_64.exe -g -q -X -s http://igagis.crabdance.com -s http://cygwin.mirror.constant.com -P cygport,calm,%DEPS%
  - cmd: C:\cygwin\setup-x86.exe -g -q -X -s http://igagis.crabdance.com -s http://cygwin.mirror.constant.com -P cygport,calm,%DEPS%
  - ps: (new-object net.webclient).DownloadFile('http://coapp.org/files/CoApp.Tools.Powershell.msi', 'C:\CoApp.Tools.Powershell.msi')
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\CoApp.Tools.Powershell.msi', /quiet -Wait
  - ps: $env:PSModulePath = $env:PSModulePath + ';C:\Program Files (x86)\Outercurve Foundation\Modules'
  - ps: Import-Module CoApp

before_build:
  - cmd: xcopy /S C:\projects\build C:\cygwin64\home\appveyor\
  - cmd: xcopy /S C:\projects\build C:\cygwin\home\appveyor\
  - nuget restore msvs_solution/msvs_solution.sln

build_script:
  - cmd: if "%APPVEYOR_REPO_TAG%"=="true"
           C:\cygwin64\bin\bash -e -l -c "prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` cygwin/*.in" &&
           C:\cygwin64\bin\bash -e -l -c "cygport cygwin/*.cygport download" &&
           C:\cygwin64\bin\bash -e -l -c "cygport cygwin/*.cygport all" &&
           C:\cygwin\bin\bash -e -l -c "prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` cygwin/*.in" &&
           C:\cygwin\bin\bash -e -l -c "cygport cygwin/*.cygport download" &&
           C:\cygwin\bin\bash -e -l -c "cygport cygwin/*.cygport all"
         else
           C:\cygwin64\bin\bash -e -l -c "make" &&
           C:\cygwin\bin\bash -e -l -c "make"
  - ps: .\nuget\build_nuget.ps1

test_script:
  - cmd: C:\cygwin64\bin\bash -e -l -c "make test"
#  - cmd: C:\cygwin\bin\bash -e -l -c "make test"
#  - ps: .\tests\autotest-appveyor.ps1

before_deploy:
  - cmd: if "%APPVEYOR_REPO_TAG%"=="true" (C:\cygwin64\bin\bash -e -l -c "prorab-deploy-cygwin.sh -r igagis/cygwin-repo" && C:\cygwin\bin\bash -e -l -c "prorab-deploy-cygwin.sh -r igagis/cygwin-repo") else (echo Skipping deploy because not a tagged commit.)


deploy:
  provider: NuGet
  api_key:
    secure: cvBwlGzXt2fwZB1AFv+aJZca9hCQf4hW/BYwKOjCjCx0WFD9L6g9e2IH7SZ+P0Qf
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true

artifacts:
  - path: .\nuget\*.nupkg
  
